/**
 * MathML to OMML (Office Math Markup Language) Converter
 * Converts MathML generated by KaTeX into OMML XML wrapped in
 * MS Office conditional comments (<!--[if gte msEquation 12]>)
 * so that when copied and pasted into Microsoft Word, Word recognizes it
 * as a native, fully editable equation object.
 */

const OMML_NS = "http://schemas.microsoft.com/office/2004/12/omml";
const OMML_PREFIX = "m";

const NARY_OPERATORS = new Set([
  "\u222B", // ∫
  "\u222C", // ∬
  "\u222D", // ∭
  "\u222E", // ∮
  "\u2211", // ∑
  "\u220F", // ∏
  "\u22C3", // ⋃
  "\u22C2", // ⋂
  "\u2A01", // ⨁
  "\u2A02", // ⨂
  "\u2A0C", // ⨌
]);

const DELIM_LEFT = new Set([
  "(", "[", "{", "|", "\u2016", "\u230A", "\u2308", "\u27E8"
]);

const DELIM_RIGHT = new Set([
  ")", "]", "}", "|", "\u2016", "\u230B", "\u2309", "\u27E9"
]);

const LEFT_TO_RIGHT: Record<string, string> = {
  "(": ")",
  "[": "]",
  "{": "}",
  "|": "|",
  "\u2016": "\u2016",
  "\u230A": "\u230B",
  "\u2308": "\u2309",
  "\u27E8": "\u27E9",
};

const FUNCTION_NAMES = new Set([
  "lim", "max", "min", "sup", "inf", "det", "gcd", "lcm",
  "arg", "deg", "dim", "hom", "ker", "pr", "sin", "cos", "tan", "log", "ln", "exp"
]);

const ITALIC_CHARS = new Set(
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZαβγδεζηθικλμνξοπρστυφχψωΑΒΓΔΕΖΗΘΙΚΜΝΞΟΠΡΣΤΥΦΧΨΩ"
);

function isVariable(text: string): boolean {
  if (!text) return false;
  if (text.length === 1 && ITALIC_CHARS.has(text)) return true;
  if (/^[a-zA-Z]+$/.test(text) && !FUNCTION_NAMES.has(text.toLowerCase())) return true;
  return false;
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function buildRun(text: string, italic = false, bold = false, roman = false): string {
  const parts: string[] = [];
  if (italic || bold || roman) {
    parts.push("<m:rPr>");
    if (italic) parts.push('<m:sty m:val="i"/>');
    if (bold) parts.push('<m:sty m:val="b"/>');
    if (roman) parts.push('<m:scr m:val="roman"/><m:sty m:val="p"/>');
    parts.push("</m:rPr>");
  }
  parts.push(`<m:t>${escapeXml(text)}</m:t>`);
  return `<m:r>${parts.join("")}</m:r>`;
}

function getNodeText(node: Node): string {
  let text = "";
  if (node.nodeType === Node.TEXT_NODE) {
    text += node.nodeValue || "";
  }
  node.childNodes.forEach((child) => {
    text += getNodeText(child);
  });
  return text.trim();
}

function isNaryOpNode(node: Element): boolean {
  const tag = node.tagName.toLowerCase().replace(/.*:/, "");
  if (tag !== "mo") return false;
  const text = getNodeText(node);
  return NARY_OPERATORS.has(text);
}

function isDelimNode(node: Element, side: "left" | "right"): boolean {
  const tag = node.tagName.toLowerCase().replace(/.*:/, "");
  if (tag !== "mo") return false;
  const text = getNodeText(node);
  return side === "left" ? DELIM_LEFT.has(text) : DELIM_RIGHT.has(text);
}

class MathML2OMMLConverter {
  convert(mathmlElement: Element, isDisplay: boolean): string {
    const body = this.convertChildren(mathmlElement);
    const nsDecl = ` xmlns:${OMML_PREFIX}="${OMML_NS}"`;

    if (isDisplay) {
      return `<${OMML_PREFIX}:oMathPara${nsDecl}><${OMML_PREFIX}:oMath>${body}</${OMML_PREFIX}:oMath></${OMML_PREFIX}:oMathPara>`;
    } else {
      return `<${OMML_PREFIX}:oMath${nsDecl}>${body}</${OMML_PREFIX}:oMath>`;
    }
  }

  convertChildren(node: Element): string {
    let result = "";
    Array.from(node.children).forEach((child) => {
      const tag = child.tagName.toLowerCase().replace(/.*:/, "");
      if (tag === "annotation" || tag === "annotation-xml") return;
      result += this.convertChild(child);
    });
    return result;
  }

  convertChild(node: Element): string {
    const tag = node.tagName.toLowerCase().replace(/.*:/, "");
    switch (tag) {
      case "mrow":
        return this.tagMrow(node);
      case "mfrac":
        return this.tagMfrac(node);
      case "msup":
        return this.tagMsup(node);
      case "msub":
        return this.tagMsub(node);
      case "msubsup":
        return this.tagMsubsup(node);
      case "msqrt":
        return this.tagMsqrt(node);
      case "mroot":
        return this.tagMroot(node);
      case "mi":
        return this.tagMi(node);
      case "mn":
        return this.tagMn(node);
      case "mo":
        return this.tagMo(node);
      case "mtext":
        return this.tagMtext(node);
      case "mspace":
        return buildRun("\u00A0");
      case "mover":
        return this.tagMover(node);
      case "munder":
        return this.tagMunder(node);
      case "munderover":
        return this.tagMunderover(node);
      case "mtable":
        return this.tagMtable(node);
      case "mtr":
        return this.tagMtr(node);
      case "mtd":
        return this.tagMtd(node);
      case "semantics":
      case "mstyle":
      case "mpadded":
      case "mphantom":
      case "merror":
        return this.convertChildren(node);
      default:
        return this.tagFallback(node);
    }
  }

  tagFallback(node: Element): string {
    const text = getNodeText(node);
    if (text) return buildRun(text);
    return this.convertChildren(node);
  }

  tagMrow(node: Element): string {
    const children = Array.from(node.children).filter((c) => {
      const tag = c.tagName.toLowerCase().replace(/.*:/, "");
      return tag !== "annotation" && tag !== "annotation-xml";
    });
    if (children.length === 0) return "";

    if (children.length >= 2) {
      const first = children[0];
      const last = children[children.length - 1];
      if (isDelimNode(first, "left") && isDelimNode(last, "right")) {
        const leftChar = getNodeText(first);
        const rightChar = getNodeText(last);
        if (LEFT_TO_RIGHT[leftChar] === rightChar) {
          const innerNodes = children.slice(1, children.length - 1);
          const inner = innerNodes.map((c) => this.convertChild(c)).join("");
          return (
            `<m:d>` +
            `<m:dPr>` +
            `<m:begChr m:val="${escapeXml(leftChar)}"/>` +
            `<m:endChr m:val="${escapeXml(rightChar)}"/>` +
            `</m:dPr>` +
            `<m:e>${inner}</m:e>` +
            `</m:d>`
          );
        }
      }
    }

    return children.map((c) => this.convertChild(c)).join("");
  }

  tagMfrac(node: Element): string {
    const children = Array.from(node.children);
    const num = children[0] ? this.convertChild(children[0]) : "";
    const den = children[1] ? this.convertChild(children[1]) : "";
    const isNoBar = node.getAttribute("linethickness") === "0";

    const fprParts = [`<m:ctrlPr></m:ctrlPr>`];
    if (isNoBar) fprParts.push(`<m:type m:val="noBar"/>`);

    return (
      `<m:f>` +
      `<m:fPr>${fprParts.join("")}</m:fPr>` +
      `<m:num>${num}</m:num>` +
      `<m:den>${den}</m:den>` +
      `</m:f>`
    );
  }

  tagMsup(node: Element): string {
    const children = Array.from(node.children);
    if (children.length >= 2) {
      if (isNaryOpNode(children[0])) {
        return this.buildNary(node, false, true);
      }
      const base = this.convertChild(children[0]);
      const sup = this.convertChild(children[1]);
      return `<m:sSup><m:e>${base}</m:e><m:sup>${sup}</m:sup></m:sSup>`;
    }
    return this.convertChildren(node);
  }

  tagMsub(node: Element): string {
    const children = Array.from(node.children);
    if (children.length >= 2) {
      const baseText = getNodeText(children[0]);
      if (FUNCTION_NAMES.has(baseText.toLowerCase())) {
        return this.buildFunctionLimLow(node);
      }
      if (isNaryOpNode(children[0])) {
        return this.buildNary(node, true, false);
      }
      const base = this.convertChild(children[0]);
      const sub = this.convertChild(children[1]);
      return `<m:sSub><m:e>${base}</m:e><m:sub>${sub}</m:sub></m:sSub>`;
    }
    return this.convertChildren(node);
  }

  tagMsubsup(node: Element): string {
    const children = Array.from(node.children);
    if (children.length >= 3) {
      if (isNaryOpNode(children[0])) {
        return this.buildNary(node, true, true);
      }
      const base = this.convertChild(children[0]);
      const sub = this.convertChild(children[1]);
      const sup = this.convertChild(children[2]);
      return `<m:sSubSup><m:e>${base}</m:e><m:sub>${sub}</m:sub><m:sup>${sup}</m:sup></m:sSubSup>`;
    }
    return this.convertChildren(node);
  }

  buildNary(node: Element, hasSub: boolean, hasSup: boolean): string {
    const children = Array.from(node.children);
    const baseChar = getNodeText(children[0]);
    let subOmml = "";
    let supOmml = "";
    let idx = 1;
    if (hasSub && children[idx]) {
      subOmml = this.convertChild(children[idx]);
      idx++;
    }
    if (hasSup && children[idx]) {
      supOmml = this.convertChild(children[idx]);
    }

    return (
      `<m:nary>` +
      `<m:naryPr>` +
      `<m:chr m:val="${escapeXml(baseChar)}"/>` +
      `<m:limLoc m:val="subSup"/>` +
      `<m:ctrlPr></m:ctrlPr>` +
      `</m:naryPr>` +
      `<m:sub>${subOmml}</m:sub>` +
      `<m:sup>${supOmml}</m:sup>` +
      `<m:e></m:e>` +
      `</m:nary>`
    );
  }

  buildFunctionLimLow(node: Element): string {
    const children = Array.from(node.children);
    const nameText = getNodeText(children[0]);
    const limOmml = children[1] ? this.convertChild(children[1]) : "";
    const nameRun = buildRun(nameText, false, false, true);

    return (
      `<m:limLow>` +
      `<m:e>${nameRun}</m:e>` +
      `<m:lim>${limOmml}</m:lim>` +
      `</m:limLow>`
    );
  }

  tagMsqrt(node: Element): string {
    const body = this.convertChildren(node);
    return (
      `<m:rad>` +
      `<m:radPr><m:degHide m:val="on"/></m:radPr>` +
      `<m:deg></m:deg>` +
      `<m:e>${body}</m:e>` +
      `</m:rad>`
    );
  }

  tagMroot(node: Element): string {
    const children = Array.from(node.children);
    const base = children[0] ? this.convertChild(children[0]) : "";
    const deg = children[1] ? this.convertChild(children[1]) : "";
    return `<m:rad><m:deg>${deg}</m:deg><m:e>${base}</m:e></m:rad>`;
  }

  tagMi(node: Element): string {
    const text = getNodeText(node);
    if (!text) return "";
    const italic = isVariable(text);
    return buildRun(text, italic);
  }

  tagMn(node: Element): string {
    const text = getNodeText(node);
    if (!text) return "";
    return buildRun(text);
  }

  tagMo(node: Element): string {
    const text = getNodeText(node);
    if (!text) return "";
    return buildRun(text);
  }

  tagMtext(node: Element): string {
    const text = getNodeText(node);
    if (!text) return "";
    return buildRun(text);
  }

  tagMover(node: Element): string {
    const children = Array.from(node.children);
    if (children.length >= 2) {
      const base = this.convertChild(children[0]);
      const overText = getNodeText(children[1]);

      if (["\u2015", "\u00AF", "\u203E", "\u0305"].includes(overText)) {
        return `<m:bar><m:barPr><m:pos m:val="top"/></m:barPr><m:e>${base}</m:e></m:bar>`;
      }
      if (["\u02D9", "\u0307", "\u0302", "\u0303", "\u0301", "\u0300", "\u20D7", "\u2192", "^"].includes(overText)) {
        return `<m:acc><m:accPr><m:chr m:val="${escapeXml(overText)}"/></m:accPr><m:e>${base}</m:e></m:acc>`;
      }
      return `<m:bar><m:barPr><m:pos m:val="top"/></m:barPr><m:e>${base}</m:e></m:bar>`;
    }
    return this.convertChildren(node);
  }

  tagMunder(node: Element): string {
    const children = Array.from(node.children);
    if (children.length >= 2) {
      const base = this.convertChild(children[0]);
      return `<m:bar><m:barPr><m:pos m:val="bot"/></m:barPr><m:e>${base}</m:e></m:bar>`;
    }
    return this.convertChildren(node);
  }

  tagMunderover(node: Element): string {
    const children = Array.from(node.children);
    if (children.length >= 3) {
      const base = this.convertChild(children[0]);
      return `<m:groupChr><m:groupChrPr><m:chr m:val="&#x23DF;"/><m:pos m:val="top"/></m:groupChrPr><m:e>${base}</m:e></m:groupChr>`;
    }
    return this.convertChildren(node);
  }

  tagMtable(node: Element): string {
    const rows = this.convertChildren(node);
    const firstRow = node.querySelector("mtr");
    const colCount = firstRow ? firstRow.querySelectorAll("mtd").length : 0;
    const mcs = colCount > 0
      ? `<m:mcs><m:mc><m:mcPr><m:count m:val="${colCount}"/><m:mcJc m:val="center"/></m:mcPr></m:mc></m:mcs>`
      : "";

    return `<m:m><m:mPr><m:plcHide m:val="on"/>${mcs}</m:mPr>${rows}</m:m>`;
  }

  tagMtr(node: Element): string {
    const cells = this.convertChildren(node);
    return `<m:mr>${cells}</m:mr>`;
  }

  tagMtd(node: Element): string {
    const content = this.convertChildren(node);
    return `<m:e>${content}</m:e>`;
  }
}

export function mathmlToOmml(mathmlStr: string, isDisplay = false): string {
  if (!mathmlStr || !mathmlStr.trim()) return "";
  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(mathmlStr, "text/xml");
    const mathEl = doc.querySelector("math") || doc.documentElement;
    if (!mathEl) return "";
    const converter = new MathML2OMMLConverter();
    return converter.convert(mathEl, isDisplay);
  } catch (err) {
    console.error("Error converting MathML to OMML:", err);
    return "";
  }
}
